### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ChrisChross** [graphistry/graph-app-kit#31]
Hey Folks, I really much like what you do! Especially since you try to reduce complexity for a normally hard problem. 
Yet I'd super appreciate if you could reduce this a little further. Do you think that is possible? 
All that setup and stuff looks rather difficult to me. Would be great! 
Thank you.

**Comment by lmeyerov** [comment]
Hi @ChrisChross  Appreciate that, and it's entirely fair!

* For pure viz, you may enjoy our csv/xls no-code workflow: https://www.graphistry.com/blog/graphistry-2-35-9-no-code-graph-analysis-for-your-csvs-ha-for-multi-gpus-run-on-a100-cuda-11-0 

* ... we're pushing on getting connector configs + dashboarding to that level too :)

* Meanwhile, any particular aspects you'd especially like replaced, and how?

**Comment by lmeyerov** [comment]
Will close for now as now directly actionable. We'll keep pushing!
