### ISSUE TITLE
[ENH] graph-app-kit Quick Launch Stack needs update to v2.36.6

### ISSUE THREAD

**Issue by ffaghri1** [graphistry/graph-app-kit#50]
**Describe the bug**
The [Quick Launch](https://github.com/graphistry/graph-app-kit/blob/master/docs/setup.md) instructions bring up the v2.35.9. Needs update to v2.36.6

**Expected behavior**
Clicking on "Launch Stack" launching the latest v2.36.6

**Observed behavior**
Clicking on "Launch Stack" launches the v2.35.9

**To Reproduce**
Steps to reproduce the behavior, ideally entirely copy-pastable for running on an out-of-the-box install

1. Go to [Quick Launch](https://github.com/graphistry/graph-app-kit/blob/master/docs/setup.md) 
2. Click on 'Launch Stack'
3. Wait for complete initialization 
4. See the version

**Comment by lmeyerov** [comment]
Great, looks like `2.36.6` is public. Good time to test the new AMI-ID-finding script!

**Comment by ffaghri1** [comment]
Great, looking forward to testing it.

**Comment by lmeyerov** [comment]
... Landed as part of it https://github.com/graphistry/graph-app-kit/pull/51 :)
